In [110]:
import sqlite3
import pandas as pd

In [111]:
# Create a connection to SQLite database
conn = sqlite3.connect("sales_data.db")

print("Database created successfully!")

Database created successfully!

In [112]:
# Create a sample sales dataset

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Laptop', 'Mobile',
                'Tablet', 'Laptop', 'Mobile', 'Tablet', 'Laptop'],
    
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics',
                 'Electronics', 'Electronics', 'Electronics', 'Electronics',
                 'Electronics', 'Electronics'],
    
    'Customer': ['Alice', 'Bob', 'Charlie', 'David', 'Eva',
                 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    
    'Sales': [50000, 30000, 20000, 55000, 35000,
              22000, 60000, 40000, 25000, 65000],
    
    'Month': ['January', 'January', 'January', 'February', 'February',
              'February', 'March', 'March', 'March', 'April']
}

df = pd.DataFrame(data)

df

  Product     Category Customer  Sales     Month
0  Laptop  Electronics    Alice  50000   January
1  Mobile  Electronics      Bob  30000   January
2  Tablet  Electronics  Charlie  20000   January
3  Laptop  Electronics    David  55000  February
4  Mobile  Electronics      Eva  35000  February
5  Tablet  Electronics    Frank  22000  February
6  Laptop  Electronics    Grace  60000     March
7  Mobile  Electronics    Henry  40000     March
8  Tablet  Electronics      Ivy  25000     March
9  Laptop  Electronics     Jack  65000     April

In [113]:
# Import the DataFrame into SQLite

df.to_sql('sales', conn, if_exists='replace', index=False)

print("Dataset imported successfully into SQLite!")

Dataset imported successfully into SQLite!

In [114]:
# Display all data from the sales table

query = "SELECT * FROM sales"

result = pd.read_sql(query, conn)

result

  Product     Category Customer  Sales     Month
0  Laptop  Electronics    Alice  50000   January
1  Mobile  Electronics      Bob  30000   January
2  Tablet  Electronics  Charlie  20000   January
3  Laptop  Electronics    David  55000  February
4  Mobile  Electronics      Eva  35000  February
5  Tablet  Electronics    Frank  22000  February
6  Laptop  Electronics    Grace  60000     March
7  Mobile  Electronics    Henry  40000     March
8  Tablet  Electronics      Ivy  25000     March
9  Laptop  Electronics     Jack  65000     April

In [115]:
query = """
SELECT * FROM sales
WHERE Sales > 30000
"""

result = pd.read_sql(query, conn)

result

  Product     Category Customer  Sales     Month
0  Laptop  Electronics    Alice  50000   January
1  Laptop  Electronics    David  55000  February
2  Mobile  Electronics      Eva  35000  February
3  Laptop  Electronics    Grace  60000     March
4  Mobile  Electronics    Henry  40000     March
5  Laptop  Electronics     Jack  65000     April

In [116]:
query = """
SELECT * FROM sales
ORDER BY Sales DESC
"""

result = pd.read_sql(query, conn)

result

  Product     Category Customer  Sales     Month
0  Laptop  Electronics     Jack  65000     April
1  Laptop  Electronics    Grace  60000     March
2  Laptop  Electronics    David  55000  February
3  Laptop  Electronics    Alice  50000   January
4  Mobile  Electronics    Henry  40000     March
5  Mobile  Electronics      Eva  35000  February
6  Mobile  Electronics      Bob  30000   January
7  Tablet  Electronics      Ivy  25000     March
8  Tablet  Electronics    Frank  22000  February
9  Tablet  Electronics  Charlie  20000   January

In [117]:
query = """
SELECT * FROM sales
ORDER BY Sales DESC
LIMIT 5
"""

result = pd.read_sql(query, conn)

result

  Product     Category Customer  Sales     Month
0  Laptop  Electronics     Jack  65000     April
1  Laptop  Electronics    Grace  60000     March
2  Laptop  Electronics    David  55000  February
3  Laptop  Electronics    Alice  50000   January
4  Mobile  Electronics    Henry  40000     March

In [118]:
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Laptop       230000
1  Mobile       105000
2  Tablet        67000

In [119]:
query = """
SELECT Product, COUNT(*) AS Number_of_Transactions
FROM sales
GROUP BY Product
"""

result = pd.read_sql(query, conn)

result

  Product  Number_of_Transactions
0  Laptop                       4
1  Mobile                       3
2  Tablet                       3

In [120]:
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Laptop       230000
1  Mobile       105000
2  Tablet        67000

In [121]:
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
HAVING SUM(Sales) > 100000
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Laptop       230000
1  Mobile       105000

In [122]:
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
ORDER BY Total_Sales DESC
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Laptop       230000
1  Mobile       105000
2  Tablet        67000

In [123]:
customers_data = {
    'Customer': ['Alice', 'Bob', 'Charlie', 'David', 'Eva',
                 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    
    'City': ['Hyderabad', 'Mumbai', 'Delhi', 'Chennai', 'Bangalore',
             'Pune', 'Hyderabad', 'Mumbai', 'Delhi', 'Chennai']
}

customers_df = pd.DataFrame(customers_data)

customers_df.to_sql('customers', conn, if_exists='replace', index=False)

print("Customers table created successfully!")

Customers table created successfully!

In [124]:
customers_data = {
    'Customer': ['Alice', 'Bob', 'Charlie', 'David', 'Eva',
                 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    
    'City': ['Hyderabad', 'Mumbai', 'Delhi', 'Chennai', 'Bangalore',
             'Pune', 'Hyderabad', 'Mumbai', 'Delhi', 'Chennai']
}

customers_df = pd.DataFrame(customers_data)

customers_df.to_sql('customers', conn, if_exists='replace', index=False)

print("Customers table created successfully!")

Customers table created successfully!

In [125]:
query = """
SELECT sales.Product, sales.Customer, sales.Sales, customers.City
FROM sales
JOIN customers
ON sales.Customer = customers.Customer
"""

result = pd.read_sql(query, conn)

result

  Product Customer  Sales       City
0  Laptop    Alice  50000  Hyderabad
1  Mobile      Bob  30000     Mumbai
2  Tablet  Charlie  20000      Delhi
3  Laptop    David  55000    Chennai
4  Mobile      Eva  35000  Bangalore
5  Tablet    Frank  22000       Pune
6  Laptop    Grace  60000  Hyderabad
7  Mobile    Henry  40000     Mumbai
8  Tablet      Ivy  25000      Delhi
9  Laptop     Jack  65000    Chennai

In [126]:
query = """
SELECT Product, Customer, Sales
FROM sales
WHERE Sales > (
    SELECT AVG(Sales)
    FROM sales
)
"""

result = pd.read_sql(query, conn)

result

  Product Customer  Sales
0  Laptop    Alice  50000
1  Laptop    David  55000
2  Laptop    Grace  60000
3  Laptop     Jack  65000

In [127]:
query = """
WITH ProductSales AS (
    SELECT Product, SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Product
)
SELECT *
FROM ProductSales
WHERE Total_Sales > 100000
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Laptop       230000
1  Mobile       105000

In [128]:
query = """
SELECT Product, Customer, Sales,
       RANK() OVER (ORDER BY Sales DESC) AS Sales_Rank
FROM sales
"""

result = pd.read_sql(query, conn)

result

  Product Customer  Sales  Sales_Rank
0  Laptop     Jack  65000           1
1  Laptop    Grace  60000           2
2  Laptop    David  55000           3
3  Laptop    Alice  50000           4
4  Mobile    Henry  40000           5
5  Mobile      Eva  35000           6
6  Mobile      Bob  30000           7
7  Tablet      Ivy  25000           8
8  Tablet    Frank  22000           9
9  Tablet  Charlie  20000          10

In [129]:
conn.execute("DROP VIEW IF EXISTS High_Sales")

query = """
CREATE VIEW High_Sales AS
SELECT Product, Customer, Sales
FROM sales
WHERE Sales > 40000
"""

conn.execute(query)

print("View created successfully!")

View created successfully!

In [130]:
query = "SELECT * FROM High_Sales"

result = pd.read_sql(query, conn)

result

  Product Customer  Sales
0  Laptop    Alice  50000
1  Laptop    David  55000
2  Laptop    Grace  60000
3  Laptop     Jack  65000

In [131]:
# SQL query to calculate total sales by product

query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
ORDER BY Total_Sales DESC
"""

# Read SQL data into a Pandas DataFrame
result = pd.read_sql(query, conn)

# Display the result
print(result)

  Product  Total_Sales
0  Laptop       230000
1  Mobile       105000
2  Tablet        67000

In [132]:
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
ORDER BY Total_Sales DESC
LIMIT 1
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Laptop       230000

In [133]:
query = """
SELECT Customer, Product, Sales
FROM sales
ORDER BY Sales DESC
LIMIT 1
"""

result = pd.read_sql(query, conn)

result

  Customer Product  Sales
0     Jack  Laptop  65000

In [134]:
query = """
SELECT Month, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Month
ORDER BY Total_Sales DESC
"""

result = pd.read_sql(query, conn)

result

      Month  Total_Sales
0     March       125000
1  February       112000
2   January       100000
3     April        65000

In [135]:
query = """
SELECT Product, AVG(Sales) AS Average_Sales
FROM sales
GROUP BY Product
ORDER BY Average_Sales DESC
"""

result = pd.read_sql(query, conn)

result

  Product  Average_Sales
0  Laptop   57500.000000
1  Mobile   35000.000000
2  Tablet   22333.333333

In [136]:
query = """
SELECT Product, SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Product
ORDER BY Total_Sales ASC
LIMIT 1
"""

result = pd.read_sql(query, conn)

result

  Product  Total_Sales
0  Tablet        67000

In [137]:
query = """
SELECT Product, COUNT(*) AS Number_of_Transactions
FROM sales
GROUP BY Product
ORDER BY Number_of_Transactions DESC
"""

result = pd.read_sql(query, conn)

result

  Product  Number_of_Transactions
0  Laptop                       4
1  Tablet                       3
2  Mobile                       3

In [138]:
query = """
SELECT Customer, Product, Sales
FROM sales
WHERE Sales > 40000
ORDER BY Sales DESC
"""

result = pd.read_sql(query, conn)

result

  Customer Product  Sales
0     Jack  Laptop  65000
1    Grace  Laptop  60000
2    David  Laptop  55000
3    Alice  Laptop  50000

In [139]:
query = """
SELECT customers.City, SUM(sales.Sales) AS Total_Sales
FROM sales
JOIN customers
ON sales.Customer = customers.Customer
GROUP BY customers.City
ORDER BY Total_Sales DESC
"""

result = pd.read_sql(query, conn)

result

        City  Total_Sales
0    Chennai       120000
1  Hyderabad       110000
2     Mumbai        70000
3      Delhi        45000
4  Bangalore        35000
5       Pune        22000

In [140]:
query = """
SELECT customers.City, SUM(sales.Sales) AS Total_Sales
FROM sales
JOIN customers
ON sales.Customer = customers.Customer
GROUP BY customers.City
ORDER BY Total_Sales DESC
LIMIT 1
"""

result = pd.read_sql(query, conn)

result

      City  Total_Sales
0  Chennai       120000

In [141]:
query = """
SELECT Month, Product, MAX(Sales) AS Highest_Sales
FROM sales
GROUP BY Month
ORDER BY Highest_Sales DESC
"""

result = pd.read_sql(query, conn)

result

      Month Product  Highest_Sales
0     April  Laptop          65000
1     March  Laptop          60000
2  February  Laptop          55000
3   January  Laptop          50000

In [142]:
conn.close()

print("Database connection closed successfully!")

Database connection closed successfully!